import { jsPDF } from 'jspdf';
import type { RecommendedVenue } from '@/types/venue';
import type { UserPreferences } from '@/types/user-preferences';
import { getPriceLabel } from './utils';

/**
 * Generates a plain text summary of the plan (Markdown format)
 */
export function generateTextSummary(
  recommendations: RecommendedVenue[],
  userPreferences: UserPreferences
): string {
  let text = `${userPreferences.occasion.toUpperCase()} - VENUE RECOMMENDATIONS\n`;
  text += `Generated on ${new Date().toLocaleDateString()}\n\n`;

  text += `SEARCH DETAILS:\n`;
  text += `Location: ${userPreferences.location}\n`;
  text += `Budget: ${userPreferences.budget}\n`;
  if (userPreferences.atmosphere) text += `Atmosphere: ${userPreferences.atmosphere}\n`;
  if (userPreferences.groupSize) text += `Group Size: ${userPreferences.groupSize}\n`;
  text += `\n${'='.repeat(50)}\n\n`;

  recommendations.forEach((venue, index) => {
    text += `${index + 1}. ${venue.name.toUpperCase()}\n`;
    text += `${'—'.repeat(40)}\n`;
    text += `Address: ${venue.address}\n`;
    text += `Rating: ${venue.rating > 0 ? venue.rating.toFixed(1) + ' ⭐' : 'N/A'}\n`;
    text += `Price: ${getPriceLabel(venue.priceLevel)}\n`;
    text += `Match: ${venue.matchScore}%\n\n`;

    if (venue.aiReasoning) {
      text += `Why this venue:\n${venue.aiReasoning}\n\n`;
    }

    if (venue.pros.length > 0) {
      text += `Pros:\n${venue.pros.map((p) => `  + ${p}`).join('\n')}\n`;
    }
    if (venue.cons.length > 0) {
      text += `Considerations:\n${venue.cons.map((c) => `  - ${c}`).join('\n')}\n`;
    }
    text += `\n`;
  });

  text += `${'='.repeat(50)}\n`;
  text += `Generated by Date Night Planner\n`;

  return text;
}

/**
 * Generates and downloads a PDF version of the plan
 */
export async function generatePDF(
  recommendations: RecommendedVenue[],
  userPreferences: UserPreferences
): Promise<void> {
  // Initialize PDF
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20; // Vertical cursor position

  // Helper to add text and advance cursor
  const addText = (
    text: string,
    fontSize: number,
    fontStyle: 'normal' | 'bold' | 'italic' = 'normal',
    color: [number, number, number] = [0, 0, 0],
    align: 'left' | 'center' | 'right' = 'left'
  ) => {
    // Check page break
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(fontSize);
    doc.setFont('helvetica', fontStyle);
    doc.setTextColor(color[0], color[1], color[2]);

    if (align === 'center') {
      doc.text(text, pageWidth / 2, y, { align: 'center' });
    } else {
      // Wrap text
      const lines = doc.splitTextToSize(text, contentWidth);
      doc.text(lines, margin, y);
      // Advance y based on number of lines
      y += lines.length * (fontSize * 0.45) + 2; // Approximate line height
    }
  };

  // --- HEADER ---
  addText('Date Night & Event Plan', 22, 'bold', [79, 70, 229], 'center'); // Violet color
  y += 10;
  addText(`Occasion: ${userPreferences.occasion}`, 14, 'bold', [55, 65, 81], 'center');
  y += 5;
  addText(
    `Generated on ${new Date().toLocaleDateString()} for ${userPreferences.location}`,
    10,
    'italic',
    [107, 114, 128],
    'center'
  );
  y += 15;

  // --- PREFERENCES SUMMARY ---
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  
  addText('Preferences:', 12, 'bold');
  let prefText = `Budget: ${userPreferences.budget}`;
  if (userPreferences.atmosphere) prefText += ` • Atmosphere: ${userPreferences.atmosphere}`;
  if (userPreferences.groupSize) prefText += ` • Group: ${userPreferences.groupSize}`;
  addText(prefText, 10, 'normal', [55, 65, 81]);
  y += 10;

  // --- VENUES ---
  addText('Top Recommendations', 16, 'bold', [0, 0, 0]);
  y += 5;

  recommendations.forEach((venue, index) => {
    // Spacer between venues
    y += 5;
    
    // Check page break with buffer for venue header
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    // Venue Name & Badge
    const rankPrefix = index === 0 ? '🏆 Top Pick: ' : `${index + 1}. `;
    addText(`${rankPrefix}${venue.name}`, 14, 'bold', [17, 24, 39]);
    
    // Details Line
    const ratingStr = venue.rating > 0 ? `${venue.rating.toFixed(1)}/5 Stars` : 'No Rating';
    const priceStr = getPriceLabel(venue.priceLevel);
    addText(`${venue.address} • ${ratingStr} • ${priceStr} • ${venue.matchScore}% Match`, 10, 'normal', [75, 85, 99]);
    y += 2;

    // AI Reasoning
    if (venue.aiReasoning) {
      addText('Why this spot:', 10, 'bold', [37, 99, 235]); // Blue
      addText(venue.aiReasoning, 10, 'italic', [55, 65, 81]);
      y += 2;
    }

    // Pros
    if (venue.pros.length > 0) {
      addText('Pros: ' + venue.pros.join(' • '), 9, 'normal', [22, 163, 74]); // Green
    }
    
    // Cons
    if (venue.cons.length > 0) {
      addText('Note: ' + venue.cons.join(' • '), 9, 'normal', [220, 38, 38]); // Red
    }

    // Divider
    y += 5;
    doc.setDrawColor(240, 240, 240);
    doc.line(margin, y, pageWidth - margin, y);
    y += 5;
  });

  // --- FOOTER ---
  // Add footer to all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Powered by Date Night Planner • OpenStreetMap • WikiData • Gemini AI',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Download
  const filename = `date-night-plan-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
