import type { RecommendedVenue } from '@/types/venue';
import type { UserPreferences } from '@/types/user-preferences';
import { getPriceLabel } from './utils';

/**
 * Generates a plain text summary of the plan (Markdown format)
 */
export function generateTextSummary(
  recommendations: RecommendedVenue[],
  userPreferences: UserPreferences
): string {
  let text = `${userPreferences.occasion.toUpperCase()} - VENUE RECOMMENDATIONS\n`;
  text += `Generated on ${new Date().toLocaleDateString()}\n\n`;

  text += `SEARCH DETAILS:\n`;
  text += `Location: ${userPreferences.location}\n`;
  text += `Budget: ${userPreferences.budget}\n`;
  if (userPreferences.atmosphere) text += `Atmosphere: ${userPreferences.atmosphere}\n`;
  if (userPreferences.groupSize) text += `Group Size: ${userPreferences.groupSize}\n`;
  text += `\n${'='.repeat(50)}\n\n`;

  recommendations.forEach((venue, index) => {
    text += `${index + 1}. ${venue.name.toUpperCase()}\n`;
    text += `${'—'.repeat(40)}\n`;
    text += `Address: ${venue.address}\n`;
    text += `Rating: ${venue.rating > 0 ? venue.rating.toFixed(1) + ' ⭐' : 'N/A'}\n`;
    text += `Price: ${getPriceLabel(venue.priceLevel)}\n`;
    text += `Match: ${venue.matchScore}%\n\n`;

    if (venue.aiReasoning) {
      text += `Why this venue:\n${venue.aiReasoning}\n\n`;
    }

    if (venue.pros.length > 0) {
      text += `Pros:\n${venue.pros.map((p) => `  + ${p}`).join('\n')}\n`;
    }
    if (venue.cons.length > 0) {
      text += `Considerations:\n${venue.cons.map((c) => `  - ${c}`).join('\n')}\n`;
    }
    text += `\n`;
  });

  text += `${'='.repeat(50)}\n`;
  text += `Generated by Date Night Planner\n`;

  return text;
}

